<a href="https://colab.research.google.com/github/Anthony18xd/Practicas/blob/main/Practica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

practica

In [ ]:
# Problemas con numpy
# Crear un vector de numeros enteros 1 al 20
import numpy as np
vector = np.arange(1, 21)
print(vector)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#crear una matriz de 3*3 con valores aleatorios entre 0 y 1 (enteros)
matriz = np.random.randint(0, 2, size=(3, 3))
print(matriz)

[[0 0 1]
 [1 0 1]
 [1 1 1]]


# Redimensiona una matriz de 4x4 a una matriz de 2x8

In [ ]:
print("\n1.1 Redimensión de matriz 4x4 a 2x8:")
matriz_4x4 = np.random.randint(1, 10, size=(4, 4))
print(f"Matriz original 4x4:\n{matriz_4x4}")
matriz_2x8 = matriz_4x4.reshape(2, 8)
print(f"Matriz redimensionada 2x8:\n{matriz_2x8}")


1.1 Redimensión de matriz 4x4 a 2x8:
Matriz original 4x4:
[[1 9 9 9]
 [8 6 4 7]
 [8 3 5 1]
 [5 2 5 6]]
Matriz redimensionada 2x8:
[[1 9 9 9 8 6 4 7]
 [8 3 5 1 5 2 5 6]]


Crea un array de 10 números equidistantes entre 0 y 1


In [ ]:
print("\n1.2 Array de 10 números equidistantes entre 0 y 1:")
array_equidistante = np.linspace(0, 1, 10)
print(f"Array: {array_equidistante}")


1.2 Array de 10 números equidistantes entre 0 y 1:
Array: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Concatena dos vectores vertical y horizontalmente

In [ ]:
print("\n1.3 Concatenación de vectores:")
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([6, 7, 8, 9, 10])
print(f"Vector 1: {vector1}")
print(f"Vector 2: {vector2}")


1.3 Concatenación de vectores:
Vector 1: [1 2 3 4 5]
Vector 2: [ 6  7  8  9 10]


Concatenación vertical

In [ ]:
concat_vertical = np.vstack([vector1, vector2])
print(f"Concatenación vertical:\n{concat_vertical}")

Concatenación vertical:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Concatenación horizontal

In [ ]:
concat_horizontal = np.hstack([vector1, vector2])
print(f"Concatenación horizontal: {concat_horizontal}")

Concatenación horizontal: [ 1  2  3  4  5  6  7  8  9 10]


EJERCICIO 2: OPERACIONES MATEMÁTICAS CON VECTORES

Crear dos vectores para las operaciones

In [ ]:
vector_a = np.array([10, 20, 30, 40, 50])
vector_b = np.array([5, 10, 15, 20, 25])
print(f"Vector A: {vector_a}")
print(f"Vector B: {vector_b}")

Vector A: [10 20 30 40 50]
Vector B: [ 5 10 15 20 25]


Suma, resta, multiplicación y división

In [ ]:
print("\n2.1 Operaciones básicas:")
suma = vector_a + vector_b
resta = vector_a - vector_b
multiplicacion = vector_a * vector_b
division = vector_a / vector_b

print(f"Suma: {suma}")
print(f"Resta: {resta}")
print(f"Multiplicación: {multiplicacion}")
print(f"División: {division}")


2.1 Operaciones básicas:
Suma: [15 30 45 60 75]
Resta: [ 5 10 15 20 25]
Multiplicación: [  50  200  450  800 1250]
División: [2. 2. 2. 2. 2.]


Media, mediana y desviación estándar

In [ ]:
print("\n2.2 Estadísticas del vector A:")
media = np.mean(vector_a)
mediana = np.median(vector_a)
desviacion_estandar = np.std(vector_a)

print(f"Media: {media}")
print(f"Mediana: {mediana}")
print(f"Desviación estándar: {desviacion_estandar}")


2.2 Estadísticas del vector A:
Media: 30.0
Mediana: 30.0
Desviación estándar: 14.142135623730951


Normalización (dividir por valor máximo)

In [ ]:
print("\n2.3 Normalización:")
vector_normalizado = vector_a / np.max(vector_a)
print(f"Vector normalizado: {vector_normalizado}")


2.3 Normalización:
Vector normalizado: [0.2 0.4 0.6 0.8 1. ]


Índices de valores máximo y mínimo

In [ ]:
print("\n2.4 Índices de valores extremos:")
indice_max = np.argmax(vector_a)
indice_min = np.argmin(vector_a)
print(f"Índice del valor máximo: {indice_max} (valor: {vector_a[indice_max]})")
print(f"Índice del valor mínimo: {indice_min} (valor: {vector_a[indice_min]})")



2.4 Índices de valores extremos:
Índice del valor máximo: 4 (valor: 50)
Índice del valor mínimo: 0 (valor: 10)


Multiplicación matricial entre dos matrices 3x3

In [ ]:
print("\n2.5 Multiplicación matricial:")
matriz1_3x3 = np.random.randint(1, 5, size=(3, 3))
matriz2_3x3 = np.random.randint(1, 5, size=(3, 3))
multiplicacion_matricial = np.dot(matriz1_3x3, matriz2_3x3)

print(f"Matriz 1:\n{matriz1_3x3}")
print(f"Matriz 2:\n{matriz2_3x3}")
print(f"Multiplicación matricial:\n{multiplicacion_matricial}")


2.5 Multiplicación matricial:
Matriz 1:
[[4 2 1]
 [1 1 1]
 [3 2 3]]
Matriz 2:
[[4 1 1]
 [2 2 3]
 [2 3 2]]
Multiplicación matricial:
[[22 11 12]
 [ 8  6  6]
 [22 16 15]]


EJERCICIO 3: OPERACIONES CON NUMPY - FILTROS Y SELECCIONES

Crear vector de números enteros para las operaciones

In [ ]:
vector_numeros = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(f"Vector original: {vector_numeros}")


Vector original: [ 1  2  3  4  5  6  7  8  9 10 11 12]


Seleccionar elementos pares

In [ ]:
print("\n3.1 Elementos pares:")
elementos_pares = vector_numeros[vector_numeros % 2 == 0]
print(f"Elementos pares: {elementos_pares}")


3.1 Elementos pares:
Elementos pares: [ 2  4  6  8 10 12]


Filtrar valores mayores que 5

In [ ]:
print("\n3.2 Valores mayores que 5:")
mayores_que_5 = vector_numeros[vector_numeros > 5]
print(f"Valores mayores que 5: {mayores_que_5}")


3.2 Valores mayores que 5:
Valores mayores que 5: [ 6  7  8  9 10 11 12]


Filtrar valores iguales a cero

In [ ]:
vector_con_ceros = np.array([1, 0, 3, 0, 5, 6, 0, 8])
print(f"\n3.3 Vector con ceros: {vector_con_ceros}")
valores_cero = vector_con_ceros[vector_con_ceros == 0]
valores_no_cero = vector_con_ceros[vector_con_ceros != 0]
print(f"Valores iguales a cero: {valores_cero}")
print(f"Valores diferentes de cero: {valores_no_cero}")


3.3 Vector con ceros: [1 0 3 0 5 6 0 8]
Valores iguales a cero: [0 0 0]
Valores diferentes de cero: [1 3 5 6 8]


Filtrar valores negativos

In [ ]:
vector_con_negativos = np.array([-3, -1, 0, 2, 4, -5, 7])
print(f"\n3.4 Vector con negativos: {vector_con_negativos}")
valores_negativos = vector_con_negativos[vector_con_negativos < 0]
print(f"Valores negativos: {valores_negativos}")


3.4 Vector con negativos: [-3 -1  0  2  4 -5  7]
Valores negativos: [-3 -1 -5]


Aplicar media a valores mayores que 50

In [ ]:
vector_grandes = np.array([20, 60, 30, 80, 45, 90, 55])
print(f"\n3.5 Vector con valores grandes: {vector_grandes}")
mayores_50 = vector_grandes[vector_grandes > 50]
media_mayores_50 = np.mean(mayores_50)
print(f"Valores mayores que 50: {mayores_50}")
print(f"Media de valores mayores que 50: {media_mayores_50}")


3.5 Vector con valores grandes: [20 60 30 80 45 90 55]
Valores mayores que 50: [60 80 90 55]
Media de valores mayores que 50: 71.25


EJERCICIO 4: OPERACIONES AVANZADAS CON NUMPY

In [ ]:
# Crear vector de 10 elementos y reemplazar valores mayores que 5 con 0
print("\n4.1 Reemplazar valores mayores que 5 con 0:")
vector_10 = np.array([1, 3, 6, 2, 8, 4, 9, 5, 7, 10])
print(f"Vector original: {vector_10}")
vector_modificado = vector_10.copy()
vector_modificado[vector_modificado > 5] = 0
print(f"Vector modificado: {vector_modificado}")


4.1 Reemplazar valores mayores que 5 con 0:
Vector original: [ 1  3  6  2  8  4  9  5  7 10]
Vector modificado: [1 3 0 2 0 4 0 5 0 0]


In [ ]:
# Combinar dos vectores booleanos con AND y OR
print("\n4.2 Operaciones booleanas:")
bool_vector1 = np.array([True, False, True, False, True])
bool_vector2 = np.array([True, True, False, False, True])
print(f"Vector booleano 1: {bool_vector1}")
print(f"Vector booleano 2: {bool_vector2}")

and_result = bool_vector1 & bool_vector2
or_result = bool_vector1 | bool_vector2
print(f"AND result: {and_result}")
print(f"OR result: {or_result}")


4.2 Operaciones booleanas:
Vector booleano 1: [ True False  True False  True]
Vector booleano 2: [ True  True False False  True]
AND result: [ True False False False  True]
OR result: [ True  True  True False  True]


In [ ]:
# Contar valores múltiplos de 3
print("\n4.3 Contar múltiplos de 3:")
vector_multiples = np.array([3, 6, 7, 9, 12, 15, 18, 20, 21, 24])
print(f"Vector: {vector_multiples}")
multiples_3 = vector_multiples[vector_multiples % 3 == 0]
cantidad_multiples_3 = len(multiples_3)
print(f"Múltiplos de 3: {multiples_3}")
print(f"Cantidad de múltiplos de 3: {cantidad_multiples_3}")


4.3 Contar múltiplos de 3:
Vector: [ 3  6  7  9 12 15 18 20 21 24]
Múltiplos de 3: [ 3  6  9 12 15 18 21 24]
Cantidad de múltiplos de 3: 8


In [ ]:
# Encontrar índices de elementos no nulos
print("\n4.4 Índices de elementos no nulos:")
vector_nulos = np.array([0, 3, 0, 7, 0, 9, 2])
print(f"Vector con nulos: {vector_nulos}")
indices_no_nulos = np.nonzero(vector_nulos)[0]
print(f"Índices de elementos no nulos: {indices_no_nulos}")


4.4 Índices de elementos no nulos:
Vector con nulos: [0 3 0 7 0 9 2]
Índices de elementos no nulos: [1 3 5 6]


In [ ]:
# Comprobar si todos los elementos son mayores que un valor
print("\n4.5 Verificar condiciones:")
vector_verificar = np.array([10, 15, 20, 25, 30])
valor_referencia = int(input("Ingresa un valor para comparar con todos los elementos: "))
todos_mayores = np.all(vector_verificar > valor_referencia)
print(f"Vector: {vector_verificar}")
print(f"¿Todos los elementos son mayores que {valor_referencia}? {todos_mayores}")


4.5 Verificar condiciones:
Ingresa un valor para comparar con todos los elementos: 15
Vector: [10 15 20 25 30]
¿Todos los elementos son mayores que 15? False


EJERCICIO 5: OPERACIONES MATEMÁTICAS AVANZADAS

In [ ]:
# Calcular el cuadrado de cada elemento
print("\n5.1 Cuadrado de elementos:")
vector_cuadrados = np.array([1, 2, 3, 4, 5])
print(f"Vector original: {vector_cuadrados}")
cuadrados = np.square(vector_cuadrados)
# También se puede usar: cuadrados = vector_cuadrados ** 2
print(f"Cuadrados: {cuadrados}")


5.1 Cuadrado de elementos:
Vector original: [1 2 3 4 5]
Cuadrados: [ 1  4  9 16 25]


In [ ]:
# Función exponencial
print("\n5.2 Función exponencial:")
vector_exponencial = np.array([1, 2, 3, 4])
print(f"Vector original: {vector_exponencial}")
exponenciales = np.exp(vector_exponencial)
print(f"e^x para cada elemento: {exponenciales}")



5.2 Función exponencial:
Vector original: [1 2 3 4]
e^x para cada elemento: [ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
# Elevar a la misma potencia
potencia = 3
potencias = np.power(vector_exponencial, potencia)
print(f"Elementos elevados a la potencia {potencia}: {potencias}")


Elementos elevados a la potencia 3: [ 1  8 27 64]


In [ ]:
# Valores máximos y mínimos en cada fila de una matriz
print("\n5.3 Máximos y mínimos por fila:")
matriz_ejemplo = np.array([[1, 8, 3],
                          [4, 2, 9],
                          [7, 5, 6]])
print(f"Matriz:\n{matriz_ejemplo}")
max_por_fila = np.max(matriz_ejemplo, axis=1)
min_por_fila = np.min(matriz_ejemplo, axis=1)
print(f"Máximo por fila: {max_por_fila}")
print(f"Mínimo por fila: {min_por_fila}")


5.3 Máximos y mínimos por fila:
Matriz:
[[1 8 3]
 [4 2 9]
 [7 5 6]]
Máximo por fila: [8 9 7]
Mínimo por fila: [1 2 5]


In [ ]:
# Función seno y almacenar en otro vector
print("\n5.4 Función seno:")
vector_seno = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])
print(f"Vector original (radianes): {vector_seno}")
senos = np.sin(vector_seno)
print(f"Senos: {senos}")



5.4 Función seno:
Vector original (radianes): [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Senos: [0.         0.5        0.70710678 0.8660254  1.        ]


In [ ]:
# Transpuesta de matriz 3x4
print("\n5.5 Transpuesta de matriz:")
matriz_3x4 = np.array([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12]])
print(f"Matriz original 3x4:\n{matriz_3x4}")
transpuesta = matriz_3x4.T
print(f"Matriz transpuesta 4x3:\n{transpuesta}")



5.5 Transpuesta de matriz:
Matriz original 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Matriz transpuesta 4x3:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


EJERCICIO 6: DATAFRAMES CON PANDAS

In [ ]:
# Crear DataFrame con las columnas especificadas
print("\n6.1 Creación del DataFrame:")

# Generar datos aleatorios para el DataFrame
nombres = ['Ana García', 'Luis Rodriguez', 'María López', 'Carlos Martín', 'Sofia Chen',
           'Diego Ruiz', 'Laura Fernández', 'Miguel Torres', 'Carmen Silva', 'Jorge Vega',
           'Isabella Cruz', 'Andrés Morales']

edades = [22, 28, 19, 35, 26, 31, 24, 29, 33, 27, 21, 30]

ciudades = ['Lima', 'Arequipa', 'Cusco', 'Lima', 'Trujillo', 'Lima',
            'Arequipa', 'Cusco', 'Lima', 'Trujillo', 'Lima', 'Arequipa']

# Crear DataFrame
df = pd.DataFrame({
    'Nombre': nombres,
    'Edad': edades,
    'Ciudad': ciudades
})

print("DataFrame original:")
print(df)
print(f"\nForma del DataFrame: {df.shape}")


6.1 Creación del DataFrame:
DataFrame original:
             Nombre  Edad    Ciudad
0        Ana García    22      Lima
1    Luis Rodriguez    28  Arequipa
2       María López    19     Cusco
3     Carlos Martín    35      Lima
4        Sofia Chen    26  Trujillo
5        Diego Ruiz    31      Lima
6   Laura Fernández    24  Arequipa
7     Miguel Torres    29     Cusco
8      Carmen Silva    33      Lima
9        Jorge Vega    27  Trujillo
10    Isabella Cruz    21      Lima
11   Andrés Morales    30  Arequipa

Forma del DataFrame: (12, 3)


In [ ]:
# Filtrar personas que tienen más de 25 años
print("\n6.2 Filtro: Personas mayores de 25 años:")
mayores_25 = df[df['Edad'] > 25]
print(mayores_25)


6.2 Filtro: Personas mayores de 25 años:
            Nombre  Edad    Ciudad
1   Luis Rodriguez    28  Arequipa
3    Carlos Martín    35      Lima
4       Sofia Chen    26  Trujillo
5       Diego Ruiz    31      Lima
7    Miguel Torres    29     Cusco
8     Carmen Silva    33      Lima
9       Jorge Vega    27  Trujillo
11  Andrés Morales    30  Arequipa


In [ ]:
# Añadir nueva columna 'Ingresos' con valores aleatorios
print("\n6.3 Añadir columna 'Ingresos':")
np.random.seed(42)  # Para reproducibilidad
ingresos = np.random.randint(2000, 8000, size=len(df))
df['Ingresos'] = ingresos
print(df)


6.3 Añadir columna 'Ingresos':
             Nombre  Edad    Ciudad  Ingresos
0        Ana García    22      Lima      2860
1    Luis Rodriguez    28  Arequipa      7390
2       María López    19     Cusco      7226
3     Carlos Martín    35      Lima      7191
4        Sofia Chen    26  Trujillo      5772
5        Diego Ruiz    31      Lima      5092
6   Laura Fernández    24  Arequipa      7734
7     Miguel Torres    29     Cusco      2466
8      Carmen Silva    33      Lima      7334
9        Jorge Vega    27  Trujillo      6426
10    Isabella Cruz    21      Lima      7578
11   Andrés Morales    30  Arequipa      5444


In [ ]:
# Encontrar promedio de edad
print("\n6.4 Promedio de edad:")
promedio_edad = df['Edad'].mean()
print(f"Promedio de edad: {promedio_edad:.2f} años")



6.4 Promedio de edad:
Promedio de edad: 27.08 años


In [ ]:
# Contar cuántas veces aparece cada ciudad
print("\n6.5 Conteo por ciudad:")
conteo_ciudades = df['Ciudad'].value_counts()
print("Conteo de personas por ciudad:")
print(conteo_ciudades)


6.5 Conteo por ciudad:
Conteo de personas por ciudad:
Ciudad
Lima        5
Arequipa    3
Cusco       2
Trujillo    2
Name: count, dtype: int64


In [ ]:
# Agrupar por ciudad y calcular promedio de edad para cada ciudad
print("\n6.6 Promedio de edad por ciudad:")
promedio_edad_ciudad = df.groupby('Ciudad')['Edad'].mean()
print("Promedio de edad por ciudad:")
print(promedio_edad_ciudad)


6.6 Promedio de edad por ciudad:
Promedio de edad por ciudad:
Ciudad
Arequipa    27.333333
Cusco       24.000000
Lima        28.400000
Trujillo    26.500000
Name: Edad, dtype: float64


In [ ]:
# Ordenar DataFrame por edad (ascendente y descendente)
print("\n6.7 Ordenamiento por edad:")
print("Ordenado por edad (ascendente):")
df_asc = df.sort_values('Edad', ascending=True)
print(df_asc)

print("\nOrdenado por edad (descendente):")
df_desc = df.sort_values('Edad', ascending=False)
print(df_desc)


6.7 Ordenamiento por edad:
Ordenado por edad (ascendente):
             Nombre  Edad    Ciudad  Ingresos
2       María López    19     Cusco      7226
10    Isabella Cruz    21      Lima      7578
0        Ana García    22      Lima      2860
6   Laura Fernández    24  Arequipa      7734
4        Sofia Chen    26  Trujillo      5772
9        Jorge Vega    27  Trujillo      6426
1    Luis Rodriguez    28  Arequipa      7390
7     Miguel Torres    29     Cusco      2466
11   Andrés Morales    30  Arequipa      5444
5        Diego Ruiz    31      Lima      5092
8      Carmen Silva    33      Lima      7334
3     Carlos Martín    35      Lima      7191

Ordenado por edad (descendente):
             Nombre  Edad    Ciudad  Ingresos
3     Carlos Martín    35      Lima      7191
8      Carmen Silva    33      Lima      7334
5        Diego Ruiz    31      Lima      5092
11   Andrés Morales    30  Arequipa      5444
7     Miguel Torres    29     Cusco      2466
1    Luis Rodriguez    28  Arequ

In [ ]:
# Estadísticas descriptivas
print("\n6.8 Estadísticas descriptivas:")
print(df.describe())


6.8 Estadísticas descriptivas:
            Edad     Ingresos
count  12.000000    12.000000
mean   27.083333  6042.750000
std     4.907477  1804.638928
min    19.000000  2466.000000
25%    23.500000  5356.000000
50%    27.500000  6808.500000
75%    30.250000  7348.000000
max    35.000000  7734.000000


EJERCICIO 7: FILTROS DE DATOS

In [ ]:
import pandas as pd

In [4]:
# Cargar el archivo CSV en un DataFrame de pandas
import pandas as pd # Added import statement

def cargar_csv_universidad():
    encodings = ['utf-8', 'latin-1', 'iso-8859-1', 'cp1252']

    for encoding in encodings:
        try:
            df = pd.read_csv('universidad.csv', encoding=encoding, delimiter=';')
            print(f"Archivo cargado exitosamente con codificación: {encoding}")
            return df
        except UnicodeDecodeError:
            continue

    print("No se pudo cargar el archivo con ninguna codificación probada")
    return None

# Cargar los datos
df_universidad = cargar_csv_universidad()

if df_universidad is not None:
    # Limpiar los nombres de las columnas (eliminar espacios)
    df_universidad.columns = df_universidad.columns.str.strip()

    # Mostrar información básica del DataFrame
    print("\n=== INFORMACIÓN DEL DATASET ===")
    print(f"Número total de registros: {len(df_universidad)}")
    print("\nPrimeras 5 filas:")
    print(df_universidad.head())

    print("\nColumnas disponibles:")
    print(df_universidad.columns.tolist())

    print("\nTipos de datos:")
    print(df_universidad.dtypes)

    # Limpiar la columna de carrera (eliminar espacios y normalizar)
    df_universidad['Carrera'] = df_universidad['Carrera'].str.strip()

Archivo cargado exitosamente con codificación: latin-1

=== INFORMACIÓN DEL DATASET ===
Número total de registros: 100

Primeras 5 filas:
  Num Control              Carrera  Semestre Inscripci—n  Id Persona
0    SeNeTe01  Lic. en nutriolog’a         7  20/05/2015           1
1    JeViPi02         Ing.Êqu’mica         8   2/05/2015           2
2    MaFeNœ03      Lic. en derecho         6   9/05/2015           3
3    WiVaL—04     Ing. en sistemas         2   3/12/2016           4
4    BaRiDe05     Ing. mecatr—nica        10   1/12/2018           5

Columnas disponibles:
['Num Control', 'Carrera', 'Semestre', 'Inscripci\x97n', 'Id Persona']

Tipos de datos:
Num Control    object
Carrera        object
Semestre        int64
Inscripci—n    object
Id Persona      int64
dtype: object


In [15]:
# Análisis 1: Contar estudiantes de Ing. en sistemas
sistemas_count = len(df_universidad[df_universidad['Carrera'] == 'Ing. en sistemas'])
print(f"ANÁLISIS 1: INGENIERÍA EN SISTEMAS")
print(f"Estudiantes de Ing. en sistemas: {sistemas_count}")

ANÁLISIS 1: INGENIERÍA EN SISTEMAS
Estudiantes de Ing. en sistemas: 13


In [16]:
# Análisis 2: Contar estudiantes de Lic. en derecho (nota: no hay "Ing. en derecho")
derecho_count = len(df_universidad[df_universidad['Carrera'] == 'Lic. en derecho'])
print(f"ANÁLISIS 2: LICENCIATURA EN DERECHO")
print(f"Estudiantes de Lic. en derecho: {derecho_count}")

ANÁLISIS 2: LICENCIATURA EN DERECHO
Estudiantes de Lic. en derecho: 17


In [14]:
# Análisis 3: Estudiantes inscritos en 2015
# Convertir la columna de inscripción a datetime
df_universidad['Inscripción_fecha'] = pd.to_datetime(df_universidad['Inscripci\x97n'], format='%d/%m/%Y', errors='coerce')
df_universidad['Año_inscripción'] = df_universidad['Inscripción_fecha'].dt.year

# Contar estudiantes inscritos en 2015
inscritos_2015_count = len(df_universidad[df_universidad['Año_inscripción'] == 2015])

print(f"ANÁLISIS 3: ESTUDIANTES INSCRITOS EN 2015")
print(f"Estudiantes inscritos en 2015: {inscritos_2015_count}")

ANÁLISIS 3: ESTUDIANTES INSCRITOS EN 2015
Estudiantes inscritos en 2015: 23


In [19]:
# Análisis 4: Estudiantes de 1° y 2° semestre
semestre_1_2 = len(df_universidad[df_universidad['Semestre'].isin([1, 2])])
semestre_1 = len(df_universidad[df_universidad['Semestre'] == 1])
semestre_2 = len(df_universidad[df_universidad['Semestre'] == 2])

print(f"ANÁLISIS 4: ESTUDIANTES DE 1° Y 2° SEMESTRE")
print(f"Estudiantes de 1° semestre: {semestre_1}")
print(f"Estudiantes de 2° semestre: {semestre_2}")
print(f"Total de estudiantes de 1° y 2° semestre: {semestre_1_2}")

ANÁLISIS 4: ESTUDIANTES DE 1° Y 2° SEMESTRE
Estudiantes de 1° semestre: 11
Estudiantes de 2° semestre: 11
Total de estudiantes de 1° y 2° semestre: 22


In [21]:
# Estadísticas adicionales
print(f"\n=== ESTADÍSTICAS ADICIONALES ===")
print("\nDistribución por carrera:")
carreras_count = df_universidad['Carrera'].value_counts()
for carrera, count in carreras_count.items():
    print(f"  {carrera}: {count} estudiantes")

print(f"\nDistribución por semestre:")
semestre_count = df_universidad['Semestre'].value_counts().sort_index()
for semestre, count in semestre_count.items():
    print(f"  Semestre {semestre}: {count} estudiantes")

print(f"\nDistribución por año de inscripción:")
año_count = df_universidad['Año_inscripción'].value_counts().sort_index()
for año, count in año_count.items():
    if not pd.isna(año):
        print(f"  {int(año)}: {count} estudiantes")


=== ESTADÍSTICAS ADICIONALES ===

Distribución por carrera:
  Ing.Êqu’mica: 20 estudiantes
  Lic. en nutriolog’a: 19 estudiantes
  Ing. mecatr—nica: 18 estudiantes
  Lic. en derecho: 17 estudiantes
  Ing. en sistemas: 13 estudiantes
  Lic. en pedagog’a: 13 estudiantes

Distribución por semestre:
  Semestre 1: 11 estudiantes
  Semestre 2: 11 estudiantes
  Semestre 3: 9 estudiantes
  Semestre 4: 12 estudiantes
  Semestre 5: 5 estudiantes
  Semestre 6: 9 estudiantes
  Semestre 7: 13 estudiantes
  Semestre 8: 12 estudiantes
  Semestre 9: 9 estudiantes
  Semestre 10: 9 estudiantes

Distribución por año de inscripción:
  2015: 23 estudiantes
  2016: 20 estudiantes
  2017: 26 estudiantes
  2018: 31 estudiantes


In [24]:
# Resumen final
print(f"\n" + "="*50)
print("RESUMEN DE RESULTADOS:")
print("="*50)
print(f"1. Estudiantes de Ing. en sistemas: {sistemas_count}")
print(f"2. Estudiantes de Lic. en derecho: {derecho_count}")
print(f"3. Estudiantes inscritos en 2015: {inscritos_2015_count}")
print(f"4. Estudiantes de 1° y 2° semestre: {semestre_1_2}")
print("="*50)


RESUMEN DE RESULTADOS:
1. Estudiantes de Ing. en sistemas: 13
2. Estudiantes de Lic. en derecho: 17
3. Estudiantes inscritos en 2015: 23
4. Estudiantes de 1° y 2° semestre: 22
